# Generated by Django 5.1.1 on 2024-10-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='service_date',
            field=models.DateField(blank=True),
        ),
    ]
