# Generated by Django 5.1.1 on 2024-10-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_servicebooking_service_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='service_date',
            field=models.DateField(),
        ),
    ]
